{% set version = "2.24.1" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: e838523d8c895fcc0b7dfa7ee1ac107de70ec7456e80e46a8af013196f429e1e
  patches:
    - fix-tests-path.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - jasper >=2.0.14
    - libpng
    - libnetcdf
    - libaec  # [not win]
    - hdf5
  run:
    - jasper >=2.0.14
    - libpng
    - libnetcdf
    - libaec  # [not win]
    - hdf5

test:
  requires:
    - perl  # [not win]
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-perl  # [win]
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005- ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
    - dtip
    - iainrussell
